const names = ["Ruth","Jackson",
"Debra","Allen",
"Gerald","Harris",
"Raymond","Carter",
"Jacqueline","Torres",
"Joseph","Nelson",
"Carlos","Sanchez",
"Ralph","Clark",
"Jean","Alexander",
"Stephen","Roberts",
"Eric","Long",
"Amanda","Scott",
"Teresa","Diaz",
"Wanda","Thomas", "Brooks",
"Rachel","Edwards",
"Christopher","Perez",
"Thomas","Baker",
"Sara","Moore",
"Chris","Bailey",
"Roger","Johnson",
"Marilyn","Thompson",
"Anthony","Evans",
"Julie","Hall",
"Paula","Phillips",
"Annie","Hernandez",
"Dorothy","Murphy",
"Alice","Howard", "Harry","Ross",
"Bruce","Cook",
"Carolyn","Morgan",
"Albert","Walker",
"Randy","Reed",
"Larry","Barnes",
"Lois","Wilson",
"Jesse","Campbell",
"Ernest","Rogers",
"Theresa","Patterson",
"Henry","Simmons",
"Michelle","Perry",
"Frank","Butler",
"Shirley"]

export default names;